### ISSUE TITLE
Error on OS X (10.13.6)

### ISSUE THREAD

**Issue by rpsimao** [jessarcher/zsh-artisan#1]
When running on my OS X, it always gave me this error:

readlink: illegal option -- f
usage: readlink [-n] [file ...]

I have to change: 
Line 49:
app=\`readlink -f "$dir/artisan"\`
to:
app=\`stat -f "$dir/artisan"\`

Now it works.

**Comment by jessarcher** [comment]
Hi @rpsimao, thanks for reporting this issue and providing your solution.

I don't have an OS X system to test this on, but `stat -f` doesn't seem to work the same way on GNU/Linux.

I've been doing a bit of research and it turns out that finding the canonical/absolute path across unix-like operating systems is more complicated than I had expected! There doesn't seem to be a caveat-free cross-platform one-liner!

I've changed the approach a little bit and no longer rely on finding the canonical path. It would be great if you could stash your fix and pull `master` to see if it's working for you now?

**Comment by erdemkeren** [comment]
I can report that it works using Mojave 10.14.1
